### ISSUE TITLE
how to set the session duration to "infinite" ? 

### ISSUE THREAD

**Issue by a-eid** [mozilla/node-client-sessions#125]

**Comment by vladikoff** [comment]
@a-eid have you tried something like `Infinity`?  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity

**Comment by DivyanshBatham** [comment]
@a-eid Why would you like to set the session duration to "Infinite"? Wouldn't it be a problem for the server in terms of memory, let's say if the user logged-in once and never opened our web application again.

**Comment by usb248** [comment]
@DivyanshBatham Do you know what mean "client side" ?

**Comment by DivyanshBatham** [comment]
@usb248 I didn't back then, I was a noob. Ask me now? Yeah I know quite well. And it gave me a big laugh at what I wrote 😅

**Comment by usb248** [comment]
@DivyanshBatham it reassures me lol
