### ISSUE TITLE
Manually decrypt cookie?

### ISSUE THREAD

**Issue by mattfordham** [mozilla/node-client-sessions#96]
I am attempting to incorporate integration tests into an application using this module. As the testing system (CasperJS) has no awareness of the back-end, I can't easily decrypt the cookies for testing. 

I can access the cookies and know the secret used on the server-side. With those two items in hand, how can I decrypt the cookies (in order to ensure their contents are as expected and use them as input for further tests)?

Thanks!

**Comment by seanmonstar** [comment]
There's a `util` property on the exported module that includes `encode` and `decode` methods.

**Comment by mattfordham** [comment]
Oh cool. I'll give that a go!
