### ISSUE TITLE
Is it at all possible to disable the encryption of cookies? 

### ISSUE THREAD

**Issue by alexbooker** [mozilla/node-client-sessions#97]
Is it at all possible to disable the encryption of cookies? I am interested to see how the cookie is represented in plain-text for educational purposes. Thank you.

**Comment by seanmonstar** [comment]
No. But at which part do you want to see? You could decode the ciphertext portion of the cookie and replace it with the plain text JSON, to see what it looks like.

**Comment by alexbooker** [comment]
Can you please show me how?

**Comment by seanmonstar** [comment]
Can you say what exactly you want to see? I'm mostly stabbing in the dark.

**Comment by alexbooker** [comment]
I understand, @seanmonstar. 

I want to see the plain-text cookie so that I can learn what data is being stored on the client. 

Thanks

**Comment by seanmonstar** [comment]
So, this is what creates the output: https://github.com/mozilla/node-client-sessions/blob/master/lib/client-sessions.js#L238-L244

The content is the `ciphertext` part. That's basically `cookieName + '=' JSON.stringify(content)`. So, you could see it via `cookieName + '=' + JSON.stringify(req[propName])`.

**Comment by alexbooker** [comment]
Thanks.
