### ISSUE TITLE
Any way to turn off encryption?

### ISSUE THREAD

**Issue by mattfordham** [mozilla/node-client-sessions#99]
For the sake of some tests I am writing, I am needing to turn off encryption of cookies in my testing environment. Is there an easy/recommended way to make this happen?

Thanks!

**Comment by seanmonstar** [comment]
There is not. You can use `.utils.decode` to decode them in your tests...

**Comment by mattfordham** [comment]
Yeah, I found that too, but as I'm testing with CasperJS (which is not Node), I havn't found a way to decode in the test context. Any creative ideas? ;)

**Comment by seanmonstar** [comment]
That's all. If you use the same key, you could duplicate what `decode` is doing in whatever Casper provides, and decrypt with the key.

**Comment by mattfordham** [comment]
Thanks for the help!
